"""add_worker_name_to_job_events

Revision ID: 95e67ee46138
Revises: ffed00e03b34
Create Date: 2026-02-06 16:00:33.945226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e67ee46138'
down_revision: Union[str, Sequence[str], None] = 'ffed00e03b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_events', sa.Column('worker_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_events', 'worker_name')
    # ### end Alembic commands ###
